export enum MkActionTypes{
  GET_ALL_PRODUCTS="[Product] get all products",
  NEW_PRODUCTS="[Product] new product",
  EDIT_PRODUCTS="[Product] edit product",
  SEARCH_PRODUCTS="[Product] searcH product",
  SELECTED_PRODUCTS="[Product] Selected product",
  DETAIL_PRODUCT="[Product] Detail product",
  DELETE_PRODUCTS="[Product] Delete product",
  UPDATE_PRODUCTS="[Product] Update product",
  CONNEXION="[CONNEXIOn] Update CONNEXION",
  DECONNEXION="[DECONNEXION] Update DECONNEXION",
  PRINTERCOMMANDE="[PRINTERCOMMANDE] Update PRINTERCOMMANDE",
  IMPRIMERCOMMANDE="[IMPRIMERCOMMANDE] Update IMPRIMERCOMMANDE",
  // LIVRAISONs
  GET_ALL_LIVRAISONS="[LIVRAISON] get all LIVRAISONs",
  NEW_LIVRAISONS="[LIVRAISON] new LIVRAISON",
  EDIT_LIVRAISONS="[LIVRAISON] edit LIVRAISON",
  SEARCH_LIVRAISONS="[LIVRAISON] searcH LIVRAISON",
  DETAIL_LIVRAISON="[LIVRAISON] Detail LIVRAISON",
  UPDATE_LIVRAISONS="[LIVRAISON] Update LIVRAISON",
    // CONSOMMATION
    GET_ALL_CONSOMMATIONS="[CONSOMMATION] get all CONSOMMATIONs",
    NEW_CONSOMMATIONS="[CONSOMMATION] new CONSOMMATION",
    EDIT_CONSOMMATIONS="[CONSOMMATION] edit CONSOMMATION",
    SEARCH_CONSOMMATIONS="[CONSOMMATION] searcH CONSOMMATION",
    SELECTED_CONSOMMATIONS="[CONSOMMATION] Selected CONSOMMATION",
    UPDATE_CONSOMMATIONS="[CONSOMMATION] Update CONSOMMATION",

  // PRESTATAIRE
  GET_ALL_MAZOUTS="[MAZOUT] get all MAZOUTs",
  EDIT_MAZOUTS="[MAZOUT] edit MAZOUT",

  //DEPENSE
  GET_ALL_DEPENSES="[DEPENSE] get all DEPENSEs",
  NEW_DEPENSES="[DEPENSE] new DEPENSE",
  SEARCH_DEPENSES="[DEPENSE] searcH DEPENSE",

    //ENGIN
    GET_ALL_ENGINS="[ENGIN] get all ENGINs",
    NEW_ENGINS="[ENGIN] new ENGIN",
    SEARCH_ENGINS="[ENGIN] searcH ENGIN"



}

export interface ActionEvent{
  type:MkActionTypes,
  payload?:any
}

export enum DataStateEnum{
  LOADING,
  LOADED,
  ERROR
}

export interface AppDataState<T>{

  dataState?:DataStateEnum;
  data?:T;
  errorMessage?:string

}
